config/routes.rb
Target::Application.routes.draw do
  get 'public_videos/show/:customer_id', to: 'public_videos#show', as: 'public_video'
  get 'check_for_new_blockages', to: 'membro_cliente/blockages#check_for_new_blockages'
  mount Ckeditor::Engine => '/ckeditor' 

  root to: 'membro_cliente/home#index' 
  namespace :frontend do 
    get 'carregamento', to: 'load#index', as: 'carregamento'
    get '/carregamento' => 'load#load', as: :carreg 
    get 'atualizar_estado', to: 'home#atualizar_estado'
  end

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  devise_for :membro_cliente, path: 'area-restrita', controllers: {registrations: 'membro_cliente/registrations'}
  namespace :membro_cliente, path: "area-restrita" do
    resources :blockages, only: [:create]
    get '/editar-senha' => 'edit_password#new', as: :edit_password
    patch '/editar-senha/password' => 'edit_password#update_password', as: :update_password
    
    root to: 'home#index'
  end

  devise_for :user, path: 'admin'
  namespace :admin do
    resources :users, :roles, :permissions, :usuarios

    get 'edit_password', to: 'users#edit_password',  as: :edit_password
    patch 'update_password', to: 'users#update_password',  as: :update_password
    put 'active_url/:slug', to: 'url_streams#active_url', as: :active_url
    put 'active_membro/:slug', to: 'membro_clientes#active_membro', as: :active_membro
    put 'active_block/:slug', to: 'blockages#active_block', as: :active_block
    resources :programs do
      collection do
        get 'search' => 'programs#search', as: :search
      end
    end   

    resources :url_streams do
      collection do
        get 'search' => 'url_streams#search', as: :search
      end
    end  


    resources :blockages do
      collection do
        get 'search' => 'blockages#search', as: :search
      end
    end 
    
    resources :customers do
      resources :membro_clientes do
        collection do
          match 'search' => 'membro_clientes#search', via: [:get, :post], as: :search        
        end
      end
      
      collection do
        match 'search' => 'customers#search', via: [:get, :post], as: :search        
      end
    end

    root to: 'dashboard#index'
  end 
end

app/models/program.rb
class Program < ApplicationRecord
    validates :title, :date_start, :date_end, :link, :image, presence: :true

    mount_uploader :image, DefaultUploader

    stringify :date_start, format: '%d/%m/%Y'
    stringify :date_end, format: '%d/%m/%Y'

end

app/controllers/admin/programs_controller.rb
class Admin::ProgramsController < Admin::ResourceController
    def search
        @collection = Program.all
        @collection = @collection.where('title LIKE ?', "%#{params[:search][:title]}%") if params[:search][:title].present?
        @collection = @collection.where('DATE(date_start) = ?', params[:search][:date_start].to_date.to_s) if params[:search][:date_start].present?
        @collection = @collection.where('DATE(date_end) = ?', params[:search][:date_end].to_date.to_s) if params[:search][:date_end].present?
        @collection = @collection.order(date_start: :desc).paginate(:page => params[:page])
        @collection = @collection.order(date_end: :desc).paginate(:page => params[:page])
        
        render :index
    end

    def show
        @program = Program.find_by_id(params[:id])
    end 

    
end

app/views/admin/programs/_form.html.slim
h2 Programa
= simple_form_for [:admin, resource], :html => { :class => 'form-horizontal' } do |f|
  section.panel.panel-default
    header.panel-heading.font-bold
      = resource.new_record? ? "Adicionar Programa" : "Editar Programa"
    .panel-body
      = f.input :title, :label => 'Titulo'

      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :date_start, as: :string, :label => 'Data de Início', input_html: { class: 'datetime', data: { :'date-format' => "DD/MM/YYYY HH:mm" } }

      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :date_end, as: :string, :label => 'Data de Encerramento', input_html: { class: 'datetime', data: { :'date-format' => "DD/MM/YYYY HH:mm" } }

      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :link, :label => 'Link do Vídeo'

      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :image, as: :image_preview, :label => 'Imagem', :input_html => { :preview_version => :preview }

      = f.hidden_field :image_cache
      - if !resource.new_record? && resource.image.present?      
        .form-group
          label.remove-image-label
            = f.check_box :remove_image, class: 'remove-image-checkbox'
            |Remover Imagem
           

  = render 'admin/shared/form_actions', f: f

app/views/admin/programs/index.html.slim
h2 Programas
.panel.panel-default
  .panel-body
    = simple_form_for :search, url: search_admin_programs_path, html: {class: 'search-form'}, method: :get do |f|
      .row
        .col-md-3
          = f.label :title, label: 'Título', required: false
          = f.input_field :title, class: 'col-md-12 form-control'
        .col-md-3
          = f.label :date_start, label: 'Data de Início', required: false
          = f.input_field :date_start, class: 'col-md-12 form-control datetime', data: { :'date-format' => "DD/MM/YYYY" }
        .col-md-3
          = f.label :date_end, label: 'Data de Encerramento', required: false
          = f.input_field :date_end, class: 'col-md-12 form-control datetime', data: { :'date-format' => "DD/MM/YYYY" }
        .col-md-1.mt-25
          = f.submit 'Buscar', class: 'btn btn-primary'
        .col-md-1.mt-25
          = link_to 'Limpar Busca', '', class: 'btn btn-warning'

-if collection.count > 5
  = render 'admin/shared/create_only'

.panel.panel-default
  .table-responsive
    table.table.table-striped.b-t.b-light
      thead
        tr
          th.text-center Titulo
          th.text-center Imagem
          th.text-center Data de Início
          th.text-center Data de Encerramento
          th.text-center(width=210) Ações
      tbody
        - collection.order(id: :desc).each do |r|
          tr
            td.text-center= raw r.title
            td.text-center= image_tag r.image_url(:thumb) if r.image.present?
            td.text-center= raw r.date_start.strftime("%d/%m/%Y")
            td.text-center= raw r.date_end.strftime("%d/%m/%Y")
            td.text-center.links-actions
              = render 'admin/shared/actions', r: r
              = link_to resource_path(r), target: "_blank", class: "btn btn-success" do
               = icon('fas', 'eye')

= render 'admin/shared/create'

app/views/admin/programs/show.html.slim
.container
  .col-sm-12.col-xs-12
    .row
      .col-sm-7.col-xs-12
        h6 Data de Publicação: #{l @blog.published_at, format: :date_month_name_year_concise}
        h2 = @blog.title
        h5 = @blog.abstract
        - if @blog.image?
          .row
            .col-sm-12.col-xs-12
              = image_tag @blog.image_url, class: 'img-responsive'
        h5 = raw @blog.content

#buttons.span12.left
  - if can? :update, resource_class
    = link_to 'Editar', edit_resource_path(resource), class: 'btn btn-success'