config/routes.rb
Target::Application.routes.draw do
  get 'public_videos/show/:customer_id', to: 'public_videos#show', as: 'public_video'
  get 'check_for_new_blockages', to: 'membro_cliente/blockages#check_for_new_blockages'
  mount Ckeditor::Engine => '/ckeditor' 

  root to: 'membro_cliente/home#index' 
  namespace :frontend do 
    get 'carregamento', to: 'load#index', as: 'carregamento'
    get '/carregamento' => 'load#load', as: :carreg 
    get 'atualizar_estado', to: 'home#atualizar_estado'
  end

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  devise_for :membro_cliente, path: 'area-restrita', controllers: {registrations: 'membro_cliente/registrations'}
  namespace :membro_cliente, path: "area-restrita" do
    resources :blockages, only: [:create]
    get '/editar-senha' => 'edit_password#new', as: :edit_password
    patch '/editar-senha/password' => 'edit_password#update_password', as: :update_password
    
    root to: 'home#index'
  end

  devise_for :user, path: 'admin'
  namespace :admin do
    resources :users, :roles, :permissions, :usuarios

    get 'edit_password', to: 'users#edit_password',  as: :edit_password
    patch 'update_password', to: 'users#update_password',  as: :update_password
    put 'active_url/:slug', to: 'url_streams#active_url', as: :active_url
    put 'active_membro/:slug', to: 'membro_clientes#active_membro', as: :active_membro
    put 'active_block/:slug', to: 'blockages#active_block', as: :active_block
    resources :programs do
      collection do
        get 'search' => 'programs#search', as: :search
      end
    end   

    resources :url_streams do
      collection do
        get 'search' => 'url_streams#search', as: :search
      end
    end  


    resources :blockages do
      collection do
        get 'search' => 'blockages#search', as: :search
      end
    end 
    
    resources :customers do
      resources :membro_clientes do
        collection do
          match 'search' => 'membro_clientes#search', via: [:get, :post], as: :search        
        end
      end
      
      collection do
        match 'search' => 'customers#search', via: [:get, :post], as: :search        
      end
    end

    root to: 'dashboard#index'
  end 
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates :razao_social, presence: true
    validates :nome_fantasia, presence: true
    validates :cnpj, presence: true
    validates :telefone, presence: true
    validates :email, presence: true
    has_many :membro_clientes
    # has_many :users 
    # has_many :blockages
    # has_one :url_streams 
    
    has_one :url_streams_customers, dependent: :destroy
    has_one :url_streams, through: :url_streams_customers

    has_many :blockage_customers, dependent: :destroy
    has_many :blockages, through: :blockage_customers

    has_many :user_customers, dependent: :destroy
    has_many :users, through: :user_customers
    ransackable_attributes('razao_social_or_nome_fantasia_or_cnpj_or_telefone_or_email')
   
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::ResourceController
    def index    
        @q = Customer.ransack(params[:q])
        @customer = @q.result(distinct: true)
        @collection = Customer.order(created_at: :asc).all  
    end 


    def search
    authorize! :search, Customer
    @q = Customer.ransack(params[:q])
    # @collection = @q.result(distinct: true).order(created_at: :asc).paginate(page: params[:page])
    # @collection = @q.result(distinct: true).order(created_at: :asc).where(nome_fantasia: params[:q][:nome_fantasia])
    if params[:q] && params[:q][:nome_fantasia].present?
        search_term = "%#{params[:q][:nome_fantasia]}%"
        @collection = @q.result(distinct: true).order(created_at: :asc).where("nome_fantasia ILIKE ?", search_term)
    end 

    if params[:q] && params[:q][:email].present?
        @collection = @q.result(distinct: true).order(created_at: :asc).where(email: params[:q][:email])
    end 

    if params[:q] && params[:q][:nome_fantasia].present? && params[:q][:email].present?
        @collection = @q.result(distinct: true).order(created_at: :asc).where(email: params[:q][:email])
    end 
    
    if @collection == nil 
    @q = Customer.ransack(params[:q])
    @customer = @q.result(distinct: true)
    @collection = Customer.order(created_at: :asc).all
    end
    
    render :index   
    end

    def collection    
    @q.result.paginate(:page => params[:page])
    end  
    
end

app/views/admin/customers/_form.html.slim
h2 Cliente
= simple_form_for [:admin, resource], :html => { :class => 'form-horizontal' } do |f|
  section.panel.panel-default
    header.panel-heading.font-bold
      = resource.new_record? ? "Adicionar Cliente" : "Editar Cliente - #{resource.nome_fantasia}"
    .panel-body
      = f.input :razao_social, :label => 'Razão Social'    
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :nome_fantasia, :label => 'Nome Fantasia'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :cnpj, :label => 'CNPJ'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :inscricao_estadual, label: 'Inscrição Estadual'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :inscricao_municipal, label: 'Inscrição Municipal'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :endereco, label: 'Endereço'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :numero, label: 'Número'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :bairro, :label => 'Bairro'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :cep, :label => 'CEP' 
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :estado, :label => 'Estado'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :cidade, :label => 'Cidade' 
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :site, :label => 'Site'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :email, :label => 'E-mail'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :telefone, :label => 'Telefone'
      /.line.line-dashed.b-b.line-lg.pull-in
      /= f.association :url_streams, label: 'URL Stream Selecionado'
      .line.line-dashed.b-b.line-lg.pull-in
      = f.input :campo, :label => 'Campo', :as => :ckeditor, :input_html => { :ckeditor => { :toolbar => 'Pure' } }

  = render 'admin/shared/form_actions', f: f

app/views/admin/customers/index.html.slim
h2 Clientes
.panel.panel-default
  .panel-body
    = simple_form_for @q, url: search_admin_customers_path, html: {class: 'search-form'}, method: :get do |f|
      .row
        .col-md-4
          = f.label :nome, label: 'Nome Fantasia', required: false
          = f.input_field :nome_fantasia, class: 'col-md-12 form-control' 
        .col-md-4
          = f.label :email, label: 'E-mail', required: false
          = f.input_field :email, class: 'col-md-12 form-control'      

        .col-md-1.mt-25
          = f.submit 'Buscar', class: 'btn btn-buscar'
        .col-md-1.mt-25
          = f.submit 'Todos', class: 'btn btn-limpar' 
  

= render 'admin/shared/create_only'
.panel.panel-default
  .table-responsive
    table.table.table-striped.b-t.b-light
      thead
        tr
          th.text-center E-mail
          th.text-center Nome Fantasia 
          th.text-center Site
          th.text-center Telefone
          th.text-center(width=300) Ações
      tbody
        - @collection.order(nome_fantasia: :asc).each do |r|
          tr          
            td.text-center= r.email 
            td.text-center= r.nome_fantasia           
            td.text-center= r.site                 
            td.text-center= r.telefone          
            td.text-center.links-actions
              = render 'admin/shared/actions_customers', r: r              
= render 'admin/shared/create_only'